//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Part_Of_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students_Exams_Answers
    {
        public int StudentID { get; set; }
        public int QuestionID { get; set; }
        public int ExamID { get; set; }
        public Nullable<int> AnswerID { get; set; }
        public Nullable<int> Grade { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Exam Exam { get; set; }
        public virtual Question Question { get; set; }
        public virtual Student Student { get; set; }
    }
}
